### ISSUE TITLE
正しく Docker Image がデプロイされていない

### ISSUE THREAD

**Issue by m1sk9** [approvers/OreOreBot2#1148]
### バグレポートの提出を行う前に

- [X] すでに[同じバグを報告するIssue](https://github.com/approvers/OreOreBot2/issues?q=)が存在しないか確認しましたか?
- [X] セキュリティーに関する不具合ではありませんか? セキュリティーに関する不具合はIssueで報告せず[適切な方法](https://github.com/approvers/OreOreBot2/security/policy#reporting-a-vulnerability)で報告してください

### バグの詳細

Release CI が正しく動作せず, Docker Image がデプロイされていない.

![CleanShot 2023-10-23 at 17 48 41](https://github.com/approvers/OreOreBot2/assets/82575685/9e80440e-367a-4935-a346-1e7e6dc8a826)

![CleanShot 2023-10-23 at 17 52 27](https://github.com/approvers/OreOreBot2/assets/82575685/37352756-0d33-40ac-aa2e-eb37bb1b4598)

### 再現方法

1. Release PR を Merge する

### 期待する動作

正しく Docker Image をプッシュできる.

### はらちょのバージョン

```Text
OreOreBot2-v1.48.0
```

**Comment by MikuroXina** [comment]
[実行ログ](https://github.com/approvers/OreOreBot2/actions/runs/6567873979/job/17841351495) を見たところ, バージョン情報のオプションが正常に渡されていないようです. `steps.release.outputs` の取り出し方が正しいのかを見直してみたいです.

<details><summary>Publish the Docker package にて</summary>

```
Prepare all required actions
Getting action download info
Download action repository 'docker/metadata-action@v5' (SHA:96383f45573cb7f253c731d3b3ab81c87ef81934)
Download action repository 'docker/setup-qemu-action@v3' (SHA:68827325e0b33c7199eb31dd4e31fbe9023e06e3)
Download action repository 'docker/setup-buildx-action@v3.0.0' (SHA:f95db51fddba0c2d1ec667646a06c2ce06100226)
Download action repository 'docker/login-action@v3' (SHA:343f7c4344506bcbf9b4de18042ae17996df046d)
Download action repository 'docker/build-push-action@v5' (SHA:0565240e2d4ab88bba5387d719585280857ece09)
Run ./.github/actions/publish
  with:                             # ← ここに何もないのがおかしい
Run actions/checkout@v4
  with:
    repository: approvers/OreOreBot2
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    show-progress: true
    lfs: false
    submodules: false
    set-safe-directory: true
Syncing repository: approvers/OreOreBot2
```

</details>

**Comment by MikuroXina** [comment]
どうやらこれは [Path outputs にあたるリリース](https://github.com/google-github-actions/release-please-action#path-outputs) なので, このように設定するのが正しいようです.

```yaml
        with:
          major: ${{ steps.release.outputs.packages/bot--major }}
          minor: ${{ steps.release.outputs.packages/bot--minor }}
          patch: ${{ steps.release.outputs.packages/bot--patch }}
          sha: ${{ steps.release.outputs.packages/bot--sha }}
```
