### ISSUE TITLE
actionlintを作る

### ISSUE THREAD

**Issue by KisaragiEffective** [approvers/OreOreBot2#182]
### Corresponding Passage (該当箇所)

* `/.github/workflows/*.yml`

### Problem Analysis (問題の分析)

* `/.github/workflows/*.yml`のlintが走らないと脳に悪い

### Problem Solution (問題の解決)

* [x] 以下のワークフローを作成

```yml
name: actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    name: actionlint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: actionlint
        uses: reviewdog/action-actionlint@v1.24.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
```

### Additional Information (追加情報)

N/A
